### ISSUE TITLE
Tank Commanders and Formation Break Point

### ISSUE THREAD

**Issue by Helmaer** [JWTC2200/legionbuilder#26]
Discovered that when you add the Armoured Formation mandatory Tank Commander for +10pts (which upgrades one tank to be the HQ), then it also adds +1 to the Formation Strength and Break Point (which it should not as you are upgrading and not adding a tank).
Small but impactful, especially given the relatively small numbers in an Auxilia Armoured Formation and the more fragile morale of Auxilia Formations.

**Comment by JWTC2200** [comment]
This has been fixed, they shouldn't impact formation break points anymore now. 

Thank you!
