### ISSUE TITLE
Feature Request: Duplicate List Feature

### ISSUE THREAD

**Issue by abhasavanich** [JWTC2200/legionbuilder#27]
I find myself building a list at a certain points value (say 2000 points), and then wanting to build out a 3000 point version of that list. Right now, I would have to create a new list from scratch. I think a nice little feature would be the ability to duplicate a saved list, so that I could go to my Lists page, duplicate an existing list, and use that as the starting point for a new list.

**Comment by JWTC2200** [comment]
Done! 
Hope this makes things easier for you!
