### ISSUE TITLE
Sorting by points for the app does not work as intended

### ISSUE THREAD

**Issue by MichaelSarancik** [JWTC2200/legionbuilder#37]
The sort by points does not work as intended as the image attached to this issue is an example of me trying to sort the existing lists by points values. I would probably recommend sorting by the current points of the list (for example if a list said 750/3000 then you could sort by the first number. The reason for this is because if someone sorted their list of empty army compositions then the unfinished ones would be near the top because their current values are more likely to be closer to 0, assuming that it was sorted in ASC order).

![image_2023-12-19_195907746](https://github.com/JWTC2200/legionbuilder/assets/57106179/82280752-8ff8-4d19-a27e-f292f5c57d6d)

**Comment by JWTC2200** [comment]
*rings bell of shame*
