### ISSUE TITLE
Not possible to copy full text of roster

### ISSUE THREAD

**Issue by Szczur22** [JWTC2200/legionbuilder#45]
After adding pop-up unit sheets to roster, it is not possible to copy whole roster (to paste it into Word for printing for example) as unit names are not being selected/copied (please see screenshots).
![obraz](https://github.com/JWTC2200/legionbuilder/assets/153033211/bd3c8b7f-f3dc-486f-a39a-740f5622fef3)
![obraz](https://github.com/JWTC2200/legionbuilder/assets/153033211/b6b9179e-f5b9-4f5e-a8b7-bed58d1f389a)

**Comment by JWTC2200** [comment]
Thank you. Should allow you to select the text now.

**Comment by Szczur22** [comment]
Issue returned after last major update.

**Comment by JWTC2200** [comment]
Should work now.
