### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by jodrell** [JWTC2200/legionbuilder#56]
Hi there,

I'd love to be able to contribute to Legion Builder but am having some trouble getting it to run locally.

I can get the application server running using `npm run dev` but looking at the source code it looks like I need to define these environment variables:

```
NEXT_PUBLIC_FIREBASE_API_KEY=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
NEXT_PUBLIC_FIREBASE_DATABASEURL=
NEXT_PUBLIC_FIREBASE_PROJECT_ID=
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
NEXT_PUBLIC_FIREBASE_APP_ID=
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=
```

I'm not familiar with Firebase so I'd appreciate some help getting Firebase up and running with whatever I need to get Legion Builder running locally. I'm happy to write up the process to make it easier for future contributors.

**Comment by kirkbushell** [comment]
Firebase dos are here: https://firebase.google.com/docs?_gl=1*fa23o2*_up*MQ..&gclid=CjwKCAjwyJqzBhBaEiwAWDRJVElO3nDo3UQgxlEDr76MQrhGjGwvrAumqfjnL6jTotJgg7PiJvxqhhoCWJMQAvD_BwE&gclsrc=aw.ds
