### ISSUE TITLE
allies

### ISSUE THREAD

**Issue by rafparis** [JWTC2200/legionbuilder#6]
I have 3 detachements of Auxilia, for 1500 points, and 500 point of allies, divided in 2 titans. 
I got an error message "Too many allies!". But the list is correct, i am in the 30% range, and it was confirmed that it is 1 ally detachement per normal detachement, so having 3 i can have up to 3 allies detachements.

**Comment by JWTC2200** [comment]
Thanks. I mistakely referenced points of main faction taken instead of game size.
